name: Sync to Quizizz
on:
  push:
    paths: ['soal.json']
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Update Quiz
        run: |
          curl -X PATCH "https://quizizz.com/api/v1/quizzes/68105852a8220f5e36152b36" \
          -H "Authorization: Bearer ${{ secrets.QUIZIZZ_TOKEN }}" \
          -H "Content-Type: application/json" \
          --data-binary "@soal.json"
